export const catchHandler = (error) => {
  return { status: 500, message: 'OcurriÃ³ un error inesperado, vuelva a intentarlo mÃ¡s tarde' }
}